# Generated by Django 4.1 on 2024-04-16 12:57

from django.db import migrations
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', salesforce.fields.CharField(db_column='Name', max_length=255, verbose_name='Account Name')),
                ('billing_street', salesforce.fields.TextField(blank=True, db_column='BillingStreet', null=True)),
                ('is_active', salesforce.fields.CharField(blank=True, db_column='Active__c', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Account',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', salesforce.fields.CharField(blank=True, db_column='Name', max_length=120, null=True)),
            ],
            options={
                'db_table': 'Opportunity',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
