# Generated by Django 4.1 on 2024-04-17 07:39

import datetime
from django.db import migrations
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OppTeam',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', salesforce.fields.CharField(blank=True, max_length=255, null=True, verbose_name='OpportunityTeam__c')),
            ],
            options={
                'verbose_name': 'OppTeam',
                'verbose_name_plural': 'OppTeam',
                'db_table': 'OpportunityTeam__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='close_date',
            field=salesforce.fields.DateTimeField(db_column='CloseDate', default=datetime.date(2024, 1, 1)),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage_name',
            field=salesforce.fields.CharField(blank=True, db_column='StageName', max_length=255, null=True),
        ),
    ]
