"""
Django settings for ManageSF project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-14atlfp_c^#ub5a%u&d22*4@#)h&+tv6=97z&)39*47&apk@+q"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "SF",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ManageSF.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ManageSF.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "SaveSF",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "",
    },
    # "salesforce": {
    #     "ENGINE": "salesforce.backend",
    #     "CONSUMER_KEY": "3MVG9xfrbKQ6hBytnC5pEE29nNpT4gKjgtR_t2CZSo7epgtuySV2wnMAUCF05wjY8fK_sEZPB_OSvq3j9DALi",  # 'client_id'   in OAuth2 terminology
    #     "CONSUMER_SECRET": "53F88AF7153497102E8D584556D58057D8DE685832B4ABBD88F7E493E84E976B",  # 'client_secret'
    #     "USER": "rpabotsvc@calvettiferguson.com.partial",
    #     "PASSWORD": "Analytics24!",
    #     "HOST": "https://test.salesforce.com",
    # },
    "salesforce": {
        "ENGINE": "salesforce.backend",
        "CONSUMER_KEY": "3MVG9pRzvMkjMb6mt_SYx6nzn8qei9mZYWS0unABnHSZ5MN7bXhmH45vshh6iq0ZEyBH05yd3lIzGZIfjJO4a",  # 'client_id'   in OAuth2 terminology
        "CONSUMER_SECRET": "45161877CE23D40C28B014B2DFB6CCAF20D045146598021DE6CBD3A966CE8218",  # 'client_secret'
        "USER": "tomdao1995@gmail.com",
        "PASSWORD": "Amothaiba123!",
        "HOST": "https://login.salesforce.com",
    },
}
DATABASE_ROUTERS = ["salesforce.router.ModelRouter"]

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
